config/routes.rb
Rails.application.routes.draw do
  get 'bookings/show'

  devise_for :users
  root to: "listings#index"
  resources :listings do
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:new, :create, :show]
  end
  resources :users, only: [:show, :edit, :update] do
    resources :bookings, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  has_many :reviews
  validates :date, :duration, presence: true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :title, :description, :price, :location, :category, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_title_description_location_category_user,
                  against: %i[title description location category],
                  associated_against: {
                    user: %i[first_name last_name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :listings, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :first_name, :last_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name description location photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @listing = @booking.listing
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.listing = Listing.find(params[:listing_id])
    @booking.price = @booking.listing.price * @booking.duration
    @listing = @booking.listing
    @booking.user = @user
    respond_to do |format|
      if @booking.save
        format.html do
          redirect_to listing_booking_path(listing_id: @listing.id, id: @booking.id),
                      notice: "Booking was successfully created."
        end
      else
        format.html { redirect_to listings_path, alert: "Failed to create booking." }
      end
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :request, :duration)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    query = params[:query]
    if query.present?
      @listings = Listing.search_by_title_description_location_category_user(query)
    else
      @listings = Listing.all
    end


    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @user = @listing.user
    @booking = Booking.new
    @listings = @user.listings
    @reviews = @booking.reviews
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listings_path, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { redirect_to listings_path, alert: "Failed to create listing." }
        puts @listing.errors.full_messages.inspect
        raise
      end
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listings_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { redirect_to listings_path, alert: "Failed to update listing." }
        puts @listing.errors.full_messages.inspect
        raise
      end
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :location, :description, :price, :photo, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
    @booking = Booking.find(params[:booking_id])
    @listing = @booking.listing
    @seller = @booking.listing.user
    @buyer = @booking.user
  end

  def new
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @listing = @booking.listing
    @seller = @booking.listing.user
    @buyer = @booking.user
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html do
          redirect_to listing_review_path(listing_id: @listing.id, id: @review.id),
                      notice: "Review was successfully created."
        end
      else
        format.html { redirect_to listings_path, alert: "Failed to create review." }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1> Confirm and Pay </h1>

<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h1>Booking Confirmation</h1>
      <!-- Payment options section -->
      <div class="payment-options">
        <h2>Payment Options</h2>
        <!-- Payment form or options go here -->
      </div>
      <!-- Reviews section -->
      <div class="reviews">
        <h2>Reviews</h2>
        <!-- Reviews content goes here -->
      </div>
    </div>
    <div class="col-lg-4">
      <!-- Listing Card -->
      <div class="listing-card">
        <div class="card-body">
          <h5 class="card-title"><%= @listing.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted">
            <%= @listing.user.first_name %> <%= @listing.user.last_name %>
          </h6>
          <img src="https://media.gettyimages.com/id/1244034031/vector/cinema-poster-with-cola-film-strip-and-clapper-vector.jpg?s=612x612&w=gi&k=20&c=8ClshQC50T-wPj6CPvnPnFq1Er6Fs8fbrreXWehvdgk=" alt="Profile Picture">
          <p class="card-text">Location: <%= @listing.location %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<%= render "shared/navbar" %>

<div class="booking-container my-5 d-flex justify-content-center">
  <div class="row">

    <%# Booking confirmed %>
    <div class="col-lg-6 mr-3">
      <div class="booking-card">
        <div class="card-body text-start">
          <h5 class="card-title text-center">Booking Confirmed</h5>
          <div class="section-divider"></div>
          <br>
          <br>
          <div class="date-container">
            <span class="date text-center">
              <i class="far fa-calendar-alt fa-4x align-middle"></i>
              <p class="date-text"> <%= @booking.date %></p>
            </span>
          </div>
          <br>
          <br>
          <p class="text-start text-center">Congrats <%= @booking.user.first_name %>! </p>
          <p class="text-start text-center">You have successfully booked your slot with <%= @booking.listing.user.first_name %>.</p>
          <p class="card-text text-start text-center">Complete your payment and wait for <%= @booking.listing.user.first_name %> to confirm.</p>
          <div class="section-divider"></div>
          <br>
          <div class="show-listing-item_booking">
            <%= link_to @booking.listing, class: "show-listing-item_link" do %>
              <div class="show-listing-item_image_booking" style="background-image: url(https://cdn.discordapp.com/attachments/1105433122998325278/1113809540081795092/logo2_480.png)"></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>


    <!-- Payment summary -->
    <div class="col-lg-5 mr-3">
      <div class="booking-card">
        <div class="card-body text-start">
          <h5 class="card-title text-center">Payment Summary</h5>
          <div class="section-divider"></div>
          <div class="d-flex justify-content-between mt-3">
            <p class="card-text text-start">Total</p>
            <p class="card-text text-start"><%= number_to_currency(@booking.price, unit: '€') %></p>
          </div>
          <div class="d-flex justify-content-between mt-3">
            <p class="card-text text-start">GST(10%)</p>
            <p class="card-text text-start"><%= number_to_currency(@booking.price * 0.1, unit: '€') %></p>
          </div>
          <div class="section-divider"></div>
          <div class="d-flex justify-content-between mt-3">
            <p class="card-text text-start">Amount to pay</p>
            <p class="card-text text-start"><%= number_to_currency(@booking.price + @booking.price * 0.1, unit: '€') %></p>
          </div>
          <div class="section-divider"></div>
          <div class="payment-card">
            <div class="card">
              <div class="accordion" id="accordionExample">
                <div class="card">
                  <div class="card-header p-0" id="headingTwo">
                    <h2 class="mb-0">
                      <button class="btn btn-light btn-block text-left collapsed p-3 rounded-0 border-bottom-custom" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <div class="d-flex align-items-center justify-content-between">
                          <span>Paypal</span>
                          <img src="https://i.imgur.com/7kQEsHU.png" width="30">
                        </div>
                      </button>
                    </h2>
                  </div>
                  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                      <input type="text" class="form-control" placeholder="Paypal email">
                    </div>
                  </div>
                </div>
                <div class="card">
                  <div class="card-header p-0">
                    <h2 class="mb-0">
                      <button class="btn btn-light btn-block text-left p-3 rounded-0" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <div class="d-flex align-items-center justify-content-between">
                          <span>Credit card</span>
                          <div class="icons">
                            <img src="https://i.imgur.com/2ISgYja.png" width="30">
                            <img src="https://i.imgur.com/W1vtnOV.png" width="30">
                            <img src="https://i.imgur.com/35tC99g.png" width="30">
                            <img src="https://i.imgur.com/2ISgYja.png" width="30">
                          </div>
                        </div>
                      </button>
                    </h2>
                  </div>
                  <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body payment-card-body">
                      <span class="font-weight-normal card-text">Card Number</span>
                      <div class="input">
                        <i class="fa fa-credit-card"></i>
                        <input type="text" class="form-control" placeholder="0000 0000 0000 0000">
                      </div>
                      <div class="row mt-3 mb-3">
                        <div class="col-md-6">
                          <span class="font-weight-normal card-text">Expiry Date</span>
                          <div class="input">
                            <i class="fa fa-calendar"></i>
                            <input type="text" class="form-control" placeholder="MM/YY">
                          </div>
                        </div>
                        <div class="col-md-6">
                          <span class="font-weight-normal card-text">CVC/CVV</span>
                          <div class="input">
                            <i class="fa fa-lock"></i>
                            <input type="text" class="form-control" placeholder="000">
                          </div>
                        </div>
                      </div>
                      <span class="text-muted certificate-text"><i class="fa fa-lock"></i> Your transaction is secured with SSL certificate</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <a href="#" class="confirm-button">Pay now</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieMate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="icon" type="image/x-icon" href="https://cdn.discordapp.com/attachments/1105433122998325278/1113809540081795092/logo2_480.png">
  </head>

  <body class="d-flex flex-column justify-content-between align-itens-center min-vh-100">
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/listings/_listings.html.erb
<div id="listing-partial" class="listing-card-container" data-search-target="results">
  <% listings.shuffle.each do |listing| %>
    <div class="listing_item">
      <%= link_to listing_path(listing), class: "listing-item_link" do %>
        <div class="listing-item_image" style="background-image: url(<%= listing.photo.attached? ? url_for(listing.photo) : 'https://cdn.discordapp.com/attachments/1105433122998325278/1108988901743398973/niklas_hyperrealistic_photo_portrait_closeup_Persona_3_The_Movi_a65c3693-4478-47ad-8309-db540c3efa5d.png' %>)">
          <div class="listing-item_bg"></div>
        </div>
        <div class="listing-item_content">
          <div class="listing-item_title">
            <%= listing.title %>
          </div>
          <div class="listing-item_body text-truncate">
            <%= listing.description %>
          </div>
          <div class="listing-item_detail">
            <i class="fas fa-euro-sign"></i>
            <span class="listing-item_price"><%= listing.price %></span>
          </div>
          <div class="listing-item_detail">
            <i class="fas fa-map-marker-alt"></i>
            <span class="listing-item_location"><%= listing.location %></span>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/new.html.erb
<%= render "shared/navbar" %>

<div class="container my-5">

  <h2>New listing</h2>

  <br>

  <%= simple_form_for @listing do |form| %>

    <div class="form-inputs">
      <%= form.input :title, label_html: { style: "display: block" } %>
    </div>

    <div>
      <%= form.input :description, as: :text, label_html: { style: "display: block" } %>
    </div>

    <div>
      <%= form.input :price, label_html: { style: "display: block" } %>
    </div>

    <div>
      <%= form.input :location, label_html: { style: "display: block" } %>
    </div>

    <div>
      <%= form.input :category, as: :select, collection: ["Action", "Adventure", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "History", "Horror", "Mystery", "Romance", "Sci-Fi"], label_html: { style: "display: block" } %>
    </div>

    <div class="form-group">
      <%= form.input :photo, as: :file, label: "Photo" %>
    </div>

    <br>

    <div class="form-actions">
      <%= form.submit "Add", class: 'submit-button' %>
    </div>
  <% end %>

</div>

app/views/listings/show.html.erb
<%= render "shared/navbar" %>
<div class="container my-5">
  <div class="row" data-controller="booking">
    <div class="col-lg-6">
      <div class="show-listing_item">
        <%= link_to @listing, class: "show-listing-item_link" do %>
          <div class="show-listing-item_content">
            <div class="show-listing-item_title">
              <%= @listing.title %>
            </div>
            <br>
            <div class="show-listing-item_image" style="background-image: url(<%= @listing.photo.attached? ? url_for(@listing.photo) : 'https://cdn.discordapp.com/attachments/1105433122998325278/1108988901743398973/niklas_hyperrealistic_photo_portrait_closeup_Persona_3_The_Movi_a65c3693-4478-47ad-8309-db540c3efa5d.png' %>)">
              <div class="show-listing-item_bg"></div>
            </div>
            <br>
            <div class="show-listing-item_detail">
              <i class="fas fa-euro-sign"></i>
              <span data-booking-target="price" class="show-listing-item_price"><%= @listing.price %></span>
            </div>
            <div class="show-listing-item_detail">
              <i class="fas fa-map-marker-alt"></i>
              <span class="show-listing-item_location"><%= @listing.location %></span>
            </div>

          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="booking-card">
        <div class="card-body text-start">
          <h5 class="card-title text-center">Booking Summary</h5>
          <div class="section-divider"></div>
          <%= simple_form_for [@listing, @booking] do |f| %>
            <%= f.date_field :date, input_html: {class: "date-input"} %>
            <br>
            <br>
            <%= f.input :request, input_html: { rows: "2;", class: "custom-input" } %>
            <%= f.input :duration, label: "Duration (h)", collection: 1..10, input_html: { class: "custom-input",data: { action: "input->booking#updateTotal", booking_target: "duration" } } %>
            <div class="section-divider"></div>
            <p class="card-text text-start">Total Price: <span data-booking-target="totalPrice"><%= @listing.price %>€</span></p>
            <%= f.submit "Confirm Booking", class: "confirm-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="section-card">
    <div class="row mt-4">
      <div class="col-lg-12">
        <div class="d-flex align-items-start">
          <span>
            <i class="fa-solid fa-film fa-2x"></i>
          </span>
          <h2 class="ms-4 mb-0">About This Listing</h2>
        </div>
        <br>
        <p><%= @listing.description %></p>
      </div>
    </div>
  </div>
  <div class="section-card">
    <div class="row mt-4">
      <div class="col-lg-12">
        <div class="d-flex align-items-start">
          <span>
            <i class="fa-solid fa-film fa-2x"></i>
          </span>
          <h2 class="ms-4 mb-0">About <%= @user.first_name.capitalize %></h2>
        </div>
        <br>
        <p><%= @user.description %></p>
      </div>
    </div>
  </div>
  <div class="section-card">
    <div class="row mt-4">
      <div class="col-lg-12">
        <div class="row mt-4">
          <div class="col-lg-12">
            <div class="d-flex align-items-start">
              <span>
                <i class="fa-solid fa-film fa-2x"></i>
              </span>
              <h2 class="ms-4 mb-0">Other Listings by <%= @user.first_name %></h2>
            </div>
            <div class="listing-card-container mt-4">
              <% @listings.where.not(id: @listing.id).each do |listing| %>
                <div class="listing_item">
                  <%= link_to listing_path(listing), class: "listing-item_link" do %>
                    <div class="listing-item_image" style="background-image: url(<%= listing.photo.attached? ? url_for(listing.photo) : 'https://cdn.discordapp.com/attachments/1105433122998325278/1108988901743398973/niklas_hyperrealistic_photo_portrait_closeup_Persona_3_The_Movi_a65c3693-4478-47ad-8309-db540c3efa5d.png' %>)">
                      <div class="listing-item_bg"></div>
                    </div>
                    <div class="listing-item_content">
                      <div class="listing-item_title">
                        <%= listing.title %>
                      </div>
                      <div class="listing-item_body text-truncate">
                        <%= listing.description %>
                      </div>
                      <div class="listing-item_detail">
                        <i class="fas fa-euro-sign"></i>
                        <span class="listing-item_price"><%= listing.price %></span>
                      </div>
                      <div class="listing-item_detail">
                        <i class="fas fa-map-marker-alt"></i>
                        <span class="listing-item_location"><%= listing.location %></span>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
</div>

app/views/pages/home.html.erb
<%=  %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer
        class="text-center text-lg-start text-white w-100"
        style="background-color: black"
        >
  <!-- Grid container -->
  <div class="container-fluid p-4 pb-0">
    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">
            MovieMate
          </h6>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing
            elit.
          </p>
        </div>
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none" />
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
          <p>
            <a class="text-white">Invite a Friend</a>
          </p>
          <p>
            <%# <a class="text-white">Media Center</a> %>
          </p>
          <p>
            <a class="text-white">Buy a Gift Card</a>
          </p>
          <p>
            <%# <a class="text-white">Privacy</a> %>
          </p>
          <p>
            <a class="text-white">Contact Us </a>
          </p>
        </div>
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none" />
        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">
            Useful links
          </h6>
          <p>
            <a class="text-white">Your Account</a>
          </p>
          <p>
            <a class="text-white">FAQ</a>
          </p>
          <p>
            <%# <a class="text-white">Shipping Rates</a> %>
          </p>
          <p>
            <a class="text-white">Help</a>
          </p>
        </div>
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none" />
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
          <p><i class="fas fa-home mr-3"></i> Berlin </p>
          <p><i class="fas fa-envelope mr-3"></i> info@moviemate.com</p>
          <p><i class="fas fa-phone mr-3"></i> + 49 234 5675488</p>
          <p><i class="fas fa-print mr-3"></i> + 49 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
    <hr class="my-3">
    <!-- Section: Copyright -->
    <section class="p-3 pt-0">
      <div class="row d-flex align-items-center">
        <!-- Grid column -->
        <div class="col-md-7 col-lg-8 text-center text-md-start">
          <!-- Copyright -->
          <div class="p-3">
            Copyright © 2023 MovieMate Inc. All rights reserved.
          </div>
          <!-- Copyright -->
        </div>
        <!-- Grid column -->
        <!-- Grid column -->
        <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
          <!-- Facebook -->
          <a
             class="btn btn-outline-light btn-floating m-1"
             class="text-white"
             role="button"
             ><i class="fab fa-facebook-f"></i
            ></a>
          <!-- Twitter -->
          <a
             class="btn btn-outline-light btn-floating m-1"
             class="text-white"
             role="button"
             ><i class="fab fa-twitter"></i
            ></a>
          <!-- Google -->
          <a
             class="btn btn-outline-light btn-floating m-1"
             class="text-white"
             role="button"
             ><i class="fab fa-google"></i
            ></a>
          <!-- Instagram -->
          <a
             class="btn btn-outline-light btn-floating m-1"
             class="text-white"
             role="button"
             ><i class="fab fa-instagram"></i
            ></a>
        </div>
        <!-- Grid column -->
      </div>
    </section>
    <!-- Section: Copyright -->
  </div>
  <!-- Grid container -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon py-3 sticky-top">
  <div class="container container-fluid">
    <%= link_to listings_path, class: "navbar-brand rounded-circle ms-2" do %>
      <%= image_tag "https://cdn.discordapp.com/attachments/1105433122998325278/1113050154845605941/moviemate-28893-0-removebg-preview.png" %>
    <% end %>
    <% if params[:controller] == 'listings' && params[:action] == 'index' %>
      <%= render "shared/search_bar" %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul id="menu-bg" style="width: 150px; min-height: 45px" class="navbar-nav d-flex gap-3 align-items-center justify-content-between me-auto bg-white rounded-pill px-3 py-1" data-controller="open-menu">
          <li class="position-relative">
            <a data-open-menu-target="button" data-action="click->open-menu#openMenu" href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="menu">
              <span class="menu__line"></span>
              <span class="menu__line"></span>
              <span class="menu__line"></span>
            </a>
            <nav data-open-menu-target="nav" class="nav js-nav">
              <ul data-open-menu-target="list" class="nav__list js-nav__list">
                <li class="nav__item">
                  <%= link_to "Profile", edit_user_registration_path, class: "nav__link" %>
                </li>
                <li class="nav__item">
                  <%= link_to "New listing", new_listing_path, class: "nav__link" %>
                </li>
                <li class="nav__item">
                  <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav__link" %>
                </li>
              </ul>
            </nav>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <% if current_user.photo.present? %>
                <%= image_tag  current_user.photo, class: "avatar-bordered", alt: "User image" %>
              <% else %>
                <i class="fa-regular fa-user nav-item"></i>
              <% end %>
            <% end %>
          </li>
        </ul>
      <% else %>
        <ul style="width: 120px" class="navbar-nav d-flex gap-3 align-items-center me-auto rounded-pill px-3 py-1">
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<form class="search-bar container-fluid" action="<%= listings_path %>" method="get">
  <input type="text" name="query" placeholder="Search for your MovieMate..." style="padding-left: 20px;" data-action="input->search#handleInput" data-search-target="input" />
  <button type="submit" class="btn">
    <i class="fa-solid fa-magnifying-glass"></i>
  </button>
</form>